"""initial migration

Revision ID: 6a8f66f064a2
Revises: None
Create Date: 2016-09-12 17:43:54.028633

"""

# revision identifiers, used by Alembic.
revision = '6a8f66f064a2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
